version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "06:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.2
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.16.1
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
  - dependency-name: typescript
    versions:
    - 4.2.2
